-- Wishlist schema for Supabase
-- Dashboard → SQL Editor → New query → paste → Run

create extension if not exists pgcrypto;

create table if not exists public.app_settings (
  id int primary key default 1 check (id = 1),
  admin_token text not null
);

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  title text not null,
  kaspi_url text not null,
  image_url text not null default '',
  notes text not null default '',
  priority int not null default 5 check (priority between 1 and 10),
  price int,
  reserved_by text,
  reserved_at timestamptz,
  reservation_pin_hash text,
  created_at timestamptz not null default now()
);

alter table public.app_settings enable row level security;
alter table public.items enable row level security;

drop policy if exists "items_select_anon" on public.items;
create policy "items_select_anon"
  on public.items
  for select
  to anon, authenticated
  using (true);

create or replace function public.verify_admin(p_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  expected text;
begin
  select admin_token into expected from public.app_settings where id = 1;
  return expected is not null
    and p_token is not null
    and p_token = expected;
end;
$$;

create or replace function public.reserve_item(
  p_id bigint,
  p_name text,
  p_pin text
)
returns public.items
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  row public.items;
  clean_name text;
  clean_pin text;
begin
  clean_name := trim(p_name);
  if clean_name is null or char_length(clean_name) < 2 then
    raise exception 'Укажите имя (минимум 2 символа)';
  end if;
  if char_length(clean_name) > 80 then
    clean_name := left(clean_name, 80);
  end if;

  clean_pin := trim(p_pin);
  if clean_pin is null or clean_pin !~ '^\d{4}$' then
    raise exception 'PIN должен состоять из 4 цифр';
  end if;

  select * into row from public.items where id = p_id for update;
  if not found then
    raise exception 'Подарок не найден';
  end if;
  if row.reserved_by is not null then
    raise exception 'Уже выбрал(а): %', row.reserved_by;
  end if;

  update public.items
  set
    reserved_by = clean_name,
    reserved_at = now(),
    reservation_pin_hash = crypt(clean_pin, gen_salt('bf'))
  where id = p_id
  returning * into row;

  row.reservation_pin_hash := null;
  return row;
end;
$$;

create or replace function public.unreserve_item(p_id bigint, p_pin text)
returns public.items
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  row public.items;
  clean_pin text;
begin
  clean_pin := trim(p_pin);
  if clean_pin is null or clean_pin !~ '^\d{4}$' then
    raise exception 'PIN должен состоять из 4 цифр';
  end if;

  select * into row from public.items where id = p_id for update;
  if not found then
    raise exception 'Подарок не найден';
  end if;
  if row.reserved_by is null then
    raise exception 'Подарок ещё свободен';
  end if;
  if row.reservation_pin_hash is null then
    raise exception 'Для этого выбора нужен PIN. Обратитесь к организаторам.';
  end if;
  if crypt(clean_pin, row.reservation_pin_hash) <> row.reservation_pin_hash then
    raise exception 'Неверный PIN';
  end if;

  update public.items
  set reserved_by = null, reserved_at = null, reservation_pin_hash = null
  where id = p_id
  returning * into row;

  return row;
end;
$$;

create or replace function public.admin_create_item(
  p_token text,
  p_title text,
  p_kaspi_url text,
  p_image_url text default '',
  p_notes text default '',
  p_priority int default 5,
  p_price int default null
)
returns public.items
language plpgsql
security definer
set search_path = public
as $$
declare
  row public.items;
  pri int;
begin
  if not public.verify_admin(p_token) then
    raise exception 'Нужен админ-пароль';
  end if;
  if p_title is null or trim(p_title) = '' or p_kaspi_url is null or trim(p_kaspi_url) = '' then
    raise exception 'Нужны title и kaspi_url';
  end if;

  pri := coalesce(p_priority, 5);
  if pri < 1 then pri := 1; end if;
  if pri > 10 then pri := 10; end if;

  insert into public.items (title, kaspi_url, image_url, notes, priority, price)
  values (
    trim(p_title),
    trim(p_kaspi_url),
    coalesce(trim(p_image_url), ''),
    coalesce(trim(p_notes), ''),
    pri,
    p_price
  )
  returning * into row;

  return row;
end;
$$;

create or replace function public.admin_update_item(
  p_token text,
  p_id bigint,
  p_title text default null,
  p_kaspi_url text default null,
  p_image_url text default null,
  p_notes text default null,
  p_priority int default null,
  p_price int default null
)
returns public.items
language plpgsql
security definer
set search_path = public
as $$
declare
  row public.items;
  pri int;
begin
  if not public.verify_admin(p_token) then
    raise exception 'Нужен админ-пароль';
  end if;

  if p_priority is not null then
    pri := p_priority;
    if pri < 1 then pri := 1; end if;
    if pri > 10 then pri := 10; end if;
  end if;

  update public.items
  set
    title = case when p_title is null then title else trim(p_title) end,
    kaspi_url = case when p_kaspi_url is null then kaspi_url else trim(p_kaspi_url) end,
    image_url = case when p_image_url is null then image_url else trim(p_image_url) end,
    notes = case when p_notes is null then notes else trim(p_notes) end,
    priority = case when p_priority is null then priority else pri end,
    price = p_price
  where id = p_id
  returning * into row;

  if not found then
    raise exception 'Подарок не найден';
  end if;

  return row;
end;
$$;

create or replace function public.admin_delete_item(p_token text, p_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted int;
begin
  if not public.verify_admin(p_token) then
    raise exception 'Нужен админ-пароль';
  end if;
  delete from public.items where id = p_id;
  get diagnostics deleted = row_count;
  if deleted = 0 then
    raise exception 'Подарок не найден';
  end if;
end;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.items to anon, authenticated;
grant execute on function public.verify_admin(text) to anon, authenticated;
grant execute on function public.reserve_item(bigint, text, text) to anon, authenticated;
grant execute on function public.unreserve_item(bigint, text) to anon, authenticated;
grant execute on function public.admin_create_item(text, text, text, text, text, int, int) to anon, authenticated;
grant execute on function public.admin_update_item(text, bigint, text, text, text, text, int, int) to anon, authenticated;
grant execute on function public.admin_delete_item(text, bigint) to anon, authenticated;

-- Change this password before sharing the site:
insert into public.app_settings (id, admin_token)
values (1, 'house2026')
on conflict (id) do update set admin_token = excluded.admin_token;

insert into public.items (title, kaspi_url, image_url, notes)
select * from (values
  (
    'Набор полотенец',
    'https://kaspi.kz/',
    'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80',
    'Пример — замени в админке'
  ),
  (
    'Чайник электрический',
    'https://kaspi.kz/',
    'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=600&q=80',
    'Любой цвет'
  )
) as v(title, kaspi_url, image_url, notes)
where not exists (select 1 from public.items limit 1);
